services:
  - type: web
    name: zerodha-frontend
    env: static
    rootDir: FRONTEND
    buildCommand: npm install && npm run build
    publishDir: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
